name: DEPLOY TO STAGING

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
    branches:    
      - develop

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: yarn install
      - name: Building the project
        run: yarn build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY }}